/* istanbul ignore file */
import type { ReactNode } from 'react';
import Head from 'next/head';

interface Props {
  children: ReactNode;
}

const Layout = ({ children }: Props): JSX.Element => (
  <div>
    <Head>
      <title>title</title>
      <meta name="description" content="Generated by create next app" />
      <link rel="icon" href="/favicon.ico" />
    </Head>

    <main>
      <h1>title</h1>
      {children}
    </main>

    <footer>
      Created by{' '}
      <a
        href="https://github.com/andweeb"
        target="_blank"
        rel="noopener noreferrer"
      >
        andweeb
      </a>{' '}
      and{' '}
      <a
        href="https://github.com/joannerd"
        target="_blank"
        rel="noopener noreferrer"
      >
        joannerd
      </a>
    </footer>
  </div>
);

export default Layout;
