name: merge-request
on:
  pull_request:
    branches: [ main, develop ]
jobs:
  check:
    name: Run typecheck, tests, linter, prettier, and build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '14'
      - name: Install packages
        run: yarn
      - name: Run typecheck
        run: yarn check:type
      - name: Run tests
        run: yarn test:cov
      - name: Run linter
        run: yarn check:lint
      - name: Run prettier
        run: yarn check:format
      - name: Check build
        run: yarn build
